[workspace]
members = ["helium", "helium-macros", "helium-ir", "helium-kernel-generator", "helium-kernel-generator/benches"]
resolver = "3"

[profile.dev]
opt-level = 1

[profile.release]
debug = true

[profile.max]
inherits = 'release'
debug = false
lto = 'thin'
codegen-units = 1
